# Generated by Django 5.2.5 on 2025-08-23 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует')], verbose_name='Статус')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название курса')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность курса')),
                ('starts_at', models.DateField(verbose_name='Начало курса')),
                ('end_at', models.DateField(verbose_name='Конец курса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('dropped', 'Отчислен')], default='active', max_length=50, verbose_name='Статус')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('completed_at', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок урока')),
                ('content', models.TextField(verbose_name='Содержание урока')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Номер урока')),
                ('starts_at', models.DateTimeField(verbose_name='Начало урока')),
                ('end_at', models.DateTimeField(verbose_name='Конец урока')),
                ('meeting_url', models.TextField(verbose_name='Ссылка на встречу')),
                ('description', models.TextField(verbose_name='Описание урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название темы')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Номер темы')),
                ('description', models.TextField(verbose_name='Описание темы')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса',
            },
        ),
        migrations.CreateModel(
            name='SheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало урока')),
                ('end_at', models.DateTimeField(verbose_name='Конец урока')),
                ('session_type', models.CharField(choices=[('lection', 'Лекция'), ('seminar', 'Семинар')], verbose_name='Тип урока')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
    ]
