# Generated by Django 5.2.5 on 2025-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='meeting_url',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Ссылка на встречу'),
        ),
    ]
