# Generated by Django 5.2.5 on 2025-08-22 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField(default=1, verbose_name='Попытка')),
                ('content', models.TextField(verbose_name='Решение')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('graded', 'Оценено'), ('get_revision', 'Нужно доработать'), ('resubmitted', 'Пересдано')], default='submitted', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('due_at', models.DateTimeField(auto_now_add=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='active', max_length=50, verbose_name='Статус задания')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальный балл')),
                ('sample_solution', models.TextField(verbose_name='Пример решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='course.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('feedback', models.TextField(verbose_name='Комментарий')),
                ('grade_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда оценено')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exercise.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Оценка задания',
                'verbose_name_plural': 'Оценки заданий',
            },
        ),
    ]
