# Generated by Django 5.2.5 on 2025-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('student', 'Учащийся'), ('admin', 'Админ'), ('instructor', 'Преподователь')], default='student', max_length=50),
        ),
    ]
